name: memogarden-test

services:
    nextjs:
        build:
            context: .
            args:
                ENV_FILE: .env.testing
            target: prod
        env_file:
            - .env.testing
        environment:
            DB_HOST: postgres
            DB_PORT: 5432
        ports:
            - ${PORT}:${PORT}
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app_network

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - ${DB_PORT}:5432
        networks:
            - app_network
        healthcheck:
            test: pg_isready -U "$DB_USER" -d "$DB_NAME"
            interval: 5s
            retries: 5
            start_period: 10s

networks:
    app_network:
        driver: bridge
