name: memogarden

services:
    nextjs:
        build:
            context: .
            target: prod
        ports:
            - "${PORT}:${PORT}"
        env_file:
            - .env
        environment:
            # Overriding these since they are managed by docker compose in the production environment
            DB_HOST: postgres
            DB_PORT: 5432
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app_network

    postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - pg_data:/var/lib/postgresql/data
        networks:
            - app_network
        healthcheck:
            test: pg_isready -U "$DB_USER" -d "$DB_NAME"
            interval: 5s
            retries: 5
            start_period: 10s

volumes:
    pg_data:

networks:
    app_network:
        driver: bridge
